version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  pinger:
    image: appcelerator/pinger:${TAG:-latest}
    networks:
      - default
    labels:
      interlock.port: 3000
      interlock.hostname: "pinger"
      interlock.domain: "*"
      interlock.ssl: "true"
      interlock.ssl_cert: "cert0.pem"
      interlock.ssl_cert_key: "cert0.pem"
      interlock.network: "ampnet"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.amp.type.user == true]
