version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  pinger:
    image: appcelerator/pinger:${TAG:-latest}
    networks:
      default:
        aliases:
          - pinger
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: ampnet
        traefik.frontend.entryPoints: "http,https"
        traefik.port: 3000
        traefik.frontend.rule: "HostRegexp: pinger.examples.{domain:.+}"
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.amp.type.user == true]
