version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  pinger:
    image: appcelerator/pinger:${TAG:-latest}
    networks:
      - default
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: "pinger.examples.*"
      VIRTUAL_PROTO: "https"
      VIRTUAL_PORT: 443
      CERT_NAME: "cert0"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.amp.type.user == true]
