version: "3"

networks:
  default:
    external:
      name: ampnet

services:
  go:
    image: htilford/go-redis-counter
    networks:
      - default
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: ampnet
        traefik.frontend.entryPoints: "http,https"
        traefik.port: 80
        traefik.frontend.rule: "HostRegexp: counter.examples.{domain:.+},go.counter.examples.{domain:.+}"
      replicas: 3
      placement:
        constraints: [node.labels.amp.type.user == true]

  redis:
    image: redis
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.amp.type.user == true]
