version: "3.3"

networks:
  default:
    external:
      name: ampnet

secrets:
  certificate_amp:
    external: true
configs:
  traefik_toml:
    external: true

services:

  proxy:
    image: traefik:roquefort
    networks:
      - default
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 5s
      labels:
        io.amp.role: "infrastructure"
        io.amp.metrics.port: "8080"
      placement:
        constraints:
        - node.labels.amp.type.route == true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #command: ["--docker", "--docker.swarmmode", "--docker.domain=localdomain", "--docker.watch", "--web", "--web.metrics.prometheus"]
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "3s"
      amp.service.stabilize.timeout: "30s"
    ports:
      - "80:80"
      - "443:443"
      - "1936:8080"
    secrets:
      - source: certificate_amp
        target: cert0.pem
        mode: 0400
    configs:
      - source: traefik_toml
        target: /etc/traefik/traefik.toml
        mode: 0700
