version: "3.3"

networks:
  default:
    external:
      name: ampnet

secrets:
  certificate_amp:
    external: true

configs:
  nginx_template:
    external: true

services:

  proxy:
    image: jwilder/nginx-proxy:latest
    networks:
      - default
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 5s
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.route == true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "3s"
      amp.service.stabilize.timeout: "30s"
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - source: certificate_amp
        target: cert0.pem
        mode: 0400
    configs:
      - source: nginx_template
        target: /app/nginx.tmpl
        mode: 0644
