version: "3.3"

networks:
  default:
    external:
      name: ampnet

volumes:
  prometheus-data:

configs:
  prometheus_alerts_rules:
    external: true

services:

  prometheus:
    image: appcelerator/amp-prometheus:${TAG:-0.15.0}
    networks:
      - default
    volumes:
      - prometheus-data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9090:9090"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "5s"
      amp.service.stabilize.timeout: "45s"
      interlock.port: 9090
      interlock.hostname: "alerts"
      interlock.domain: "*"
      interlock.ssl: "true"
      interlock.ssl_cert: "cert0.pem"
      interlock.ssl_cert_key: "cert0.pem"
      interlock.network: "ampnet"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.metrics == true
    configs:
      - source: prometheus_alerts_rules
        target: /etc/prometheus/alerts.rules
        mode: 0400
