version: "3.1"

networks:
  default:
    external:
      name: ampnet

volumes:
  grafana-data:

services:

  grafana:
    image: appcelerator/grafana-amp:1.2.5
    networks:
      - default
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "8s"
      amp.service.stabilize.timeout: "60s"
      amp.service.pull.timeout: "120s"
      interlock.port: 3000
      interlock.hostname: "dashboard"
      interlock.domain: "*"
      interlock.ssl: "true"
      interlock.ssl_cert: "cert0.pem"
      interlock.ssl_cert_key: "cert0.pem"
      interlock.network: "ampnet"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.core == true
