version: "3.1"

networks:
  default:
    external:
      name: ampnet

volumes:
  grafana-data:

services:

  grafana:
    image: appcelerator/grafana-amp:1.2.5
    networks:
      - default
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "8s"
      amp.service.stabilize.timeout: "60s"
      amp.service.pull.timeout: "120s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        traefik.enable: "true"
        traefik.docker.network: ampnet
        traefik.frontend.entryPoints: "http,https"
        traefik.backend: "dashboard"
        traefik.port: 3000
        traefik.frontend.rule: "HostRegexp: dashboard.{domain:.+}"
      placement:
        constraints:
        - node.labels.amp.type.core == true
