version: "3.1"

networks:
  default:
    external:
      name: ampnet

services:

  gateway:
    image: appcelerator/gateway:${TAG:-0.15.0}
    networks:
      - default
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "5s"
      amp.service.stabilize.timeout: "20s"
      interlock.port: 80
      interlock.hostname: "gw"
      interlock.domain: "*"
      interlock.ssl: "true"
      interlock.ssl_cert: "cert0.pem"
      interlock.ssl_cert_key: "cert0.pem"
      interlock.network: "ampnet"
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.labels.amp.type.core == true
