version: "3.1"

networks:
  default:
    external:
      name: ampnet

services:

  gateway:
    image: appcelerator/gateway:${TAG:-0.15.0}
    networks:
      - default
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "5s"
      amp.service.stabilize.timeout: "20s"
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
        traefik.enable: "true"
        traefik.docker.network: ampnet
        traefik.frontend.entryPoints: "http,https"
        traefik.backend: "gw"
        traefik.port: 80
        traefik.frontend.rule: "HostRegexp: gw.{domain:.+}"
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.labels.amp.type.core == true
